---
driver:
  name: vagrant
  customize:
    memory: 4096
  vm_hostname: node-1
  network:
    - ["private_network", {ip: '10.20.1.101'}]
  vagrantfiles:
    - test/Files/Vagrant.Disk.rb

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    roles_path: roles
    run_list:
      - role[mapr-node]
    attributes:
      ssh_keys_use_encrypted_data_bag: false
      mapr:
        cldb: ['node-1']
        zk: ['node-1']
        rm: ['node-1']
        hs: 'node-1'
        ws: ['node-1']
      ssh_keys:
        mapr: ['mapr']
  - name: simple_nodes
    data_bags_path: test/integration/data_bags
    roles_path: roles
    run_list:
      - role[mapr-node]
    attributes:
      ssh_keys_use_encrypted_data_bag: false
      mapr:
        nodes:
          node-1:
            - "cldb"
            - "zk"
            - "rm"
            - "hs"
            - "ws"
      ssh_keys:
        mapr: ['mapr']
