---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[mapr_installation::install_prereq_packages]
    attributes:
